- block:
  - name: install the firewalld package
    package:
      name: firewalld
      state: "{{ pversion }}"

  - name: enable and start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: add to kubernetes ports number
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - 6443/tcp
      - 2379-2380/tcp
      - 10250/tcp
      - 10251/tcp
      - 10252/tcp
      - 10255/tcp
      - 30000-32767/tcp
      - 179/tcp
  when: enabled_firewalld

- name: stop and disabled permanently
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: not enabled_firewalld
