---
- hosts: all

  tasks:
  - authorized_key:
      user: "{{ ansible_user }}"
      key: "{{ lookup('file', '/home/' + lookup('env', 'USER') + '/.ssh/id_rsa.pub') }}"
      #      key: "{{ lookup('file', '/home/' + lookup('env', 'USER') + '{{ k8s_public_rsa_locate }}') }}"
